from typing import Generic, Protocol, TypeVar, cast, Literal

T = TypeVar("T")
N = TypeVar("N", bound=int)

def c_struct(cls: T) -> T:
    return cls

class c_array(list[T], Generic[T, N]):
    def __init__(self, length: int):
        super().__init__([cast(T, None)] * length)

class c_int(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_int") -> "c_int": ...
    def __sub__(self, other: "c_int") -> "c_int": ...
    def __mul__(self, other: "c_int") -> "c_int": ...
    def __floordiv__(self, other: "c_int") -> "c_int": ...
    def __truediv__(self, other: "c_int") -> "c_int": ...
    def __mod__(self, other: "c_int") -> "c_int": ...
    def __pow__(self, other: "c_int") -> "c_int": ...
    def __lshift__(self, other: "c_int") -> "c_int": ...
    def __rshift__(self, other: "c_int") -> "c_int": ...
    def __and__(self, other: "c_int") -> "c_int": ...
    def __or__(self, other: "c_int") -> "c_int": ...
    def __xor__(self, other: "c_int") -> "c_int": ...
    def __neg__(self) -> "c_int": ...
    def __pos__(self) -> "c_int": ...
    def __invert__(self) -> "c_int": ...
    def __index__(self) -> int: ...

class c_uint(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_uint") -> "c_uint": ...
    def __sub__(self, other: "c_uint") -> "c_uint": ...
    def __mul__(self, other: "c_uint") -> "c_uint": ...
    def __floordiv__(self, other: "c_uint") -> "c_uint": ...
    def __truediv__(self, other: "c_uint") -> "c_uint": ...
    def __mod__(self, other: "c_uint") -> "c_uint": ...
    def __pow__(self, other: "c_uint") -> "c_uint": ...
    def __lshift__(self, other: "c_uint") -> "c_uint": ...
    def __rshift__(self, other: "c_uint") -> "c_uint": ...
    def __and__(self, other: "c_uint") -> "c_uint": ...
    def __or__(self, other: "c_uint") -> "c_uint": ...
    def __xor__(self, other: "c_uint") -> "c_uint": ...
    def __index__(self) -> int: ...

class c_short(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_short") -> "c_short": ...
    def __sub__(self, other: "c_short") -> "c_short": ...
    def __mul__(self, other: "c_short") -> "c_short": ...
    def __floordiv__(self, other: "c_short") -> "c_short": ...
    def __truediv__(self, other: "c_short") -> "c_short": ...
    def __mod__(self, other: "c_short") -> "c_short": ...
    def __index__(self) -> int: ...

class c_ushort(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_ushort") -> "c_ushort": ...
    def __sub__(self, other: "c_ushort") -> "c_ushort": ...
    def __mul__(self, other: "c_ushort") -> "c_ushort": ...
    def __floordiv__(self, other: "c_ushort") -> "c_ushort": ...
    def __truediv__(self, other: "c_ushort") -> "c_ushort": ...
    def __mod__(self, other: "c_ushort") -> "c_ushort": ...
    def __index__(self) -> int: ...

class c_long(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_long") -> "c_long": ...
    def __sub__(self, other: "c_long") -> "c_long": ...
    def __mul__(self, other: "c_long") -> "c_long": ...
    def __floordiv__(self, other: "c_long") -> "c_long": ...
    def __truediv__(self, other: "c_long") -> "c_long": ...
    def __mod__(self, other: "c_long") -> "c_long": ...
    def __pow__(self, other: "c_long") -> "c_long": ...
    def __lshift__(self, other: "c_long") -> "c_long": ...
    def __rshift__(self, other: "c_long") -> "c_long": ...
    def __index__(self) -> int: ...

class c_ulong(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_ulong") -> "c_ulong": ...
    def __sub__(self, other: "c_ulong") -> "c_ulong": ...
    def __mul__(self, other: "c_ulong") -> "c_ulong": ...
    def __floordiv__(self, other: "c_ulong") -> "c_ulong": ...
    def __truediv__(self, other: "c_ulong") -> "c_ulong": ...
    def __mod__(self, other: "c_ulong") -> "c_ulong": ...
    def __pow__(self, other: "c_ulong") -> "c_ulong": ...
    def __lshift__(self, other: "c_ulong") -> "c_ulong": ...
    def __rshift__(self, other: "c_ulong") -> "c_ulong": ...
    def __index__(self) -> int: ...

class c_longlong(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_longlong") -> "c_longlong": ...
    def __sub__(self, other: "c_longlong") -> "c_longlong": ...
    def __mul__(self, other: "c_longlong") -> "c_longlong": ...
    def __floordiv__(self, other: "c_longlong") -> "c_longlong": ...
    def __truediv__(self, other: "c_longlong") -> "c_longlong": ...
    def __mod__(self, other: "c_longlong") -> "c_longlong": ...
    def __pow__(self, other: "c_longlong") -> "c_longlong": ...
    def __lshift__(self, other: "c_longlong") -> "c_longlong": ...
    def __rshift__(self, other: "c_longlong") -> "c_longlong": ...
    def __and__(self, other: "c_longlong") -> "c_longlong": ...
    def __or__(self, other: "c_longlong") -> "c_longlong": ...
    def __xor__(self, other: "c_longlong") -> "c_longlong": ...
    def __neg__(self) -> "c_longlong": ...
    def __pos__(self) -> "c_longlong": ...
    def __invert__(self) -> "c_longlong": ...
    def __index__(self) -> int: ...

class c_ulonglong(Protocol):
    def __int__(self) -> int: ...
    def __add__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __sub__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __mul__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __floordiv__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __truediv__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __mod__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __pow__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __lshift__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __rshift__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __and__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __or__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __xor__(self, other: "c_ulonglong") -> "c_ulonglong": ...
    def __index__(self) -> int: ...

class c_float(Protocol):
    def __float__(self) -> float: ...
    def __add__(self, other: "c_float") -> "c_float": ...
    def __sub__(self, other: "c_float") -> "c_float": ...
    def __mul__(self, other: "c_float") -> "c_float": ...
    def __truediv__(self, other: "c_float") -> "c_float": ...
    def __pow__(self, other: "c_float") -> "c_float": ...
    def __neg__(self) -> "c_float": ...
    def __pos__(self) -> "c_float": ...

class c_double(Protocol):
    def __float__(self) -> float: ...
    def __add__(self, other: "c_double") -> "c_double": ...
    def __sub__(self, other: "c_double") -> "c_double": ...
    def __mul__(self, other: "c_double") -> "c_double": ...
    def __truediv__(self, other: "c_double") -> "c_double": ...
    def __pow__(self, other: "c_double") -> "c_double": ...
    def __neg__(self) -> "c_double": ...
    def __pos__(self) -> "c_double": ...

class c_char(Protocol):
    def __bytes__(self) -> bytes: ...
    def __len__(self) -> int: ...
    def decode(self, encoding: str = "utf-8") -> str: ...

class c_bool(Protocol):
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __and__(self, other: "c_bool") -> "c_bool": ...
    def __or__(self, other: "c_bool") -> "c_bool": ...
    def __xor__(self, other: "c_bool") -> "c_bool": ...
    def __invert__(self) -> "c_bool": ...

class c_void: ...
void = c_void()

__all__ = [
    "cast",
    "Literal",
    "c_struct",
    "c_array",
    "c_int",
    "c_uint",
    "c_short",
    "c_ushort",
    "c_long",
    "c_ulong",
    "c_longlong",
    "c_ulonglong",
    "c_float",
    "c_double",
    "c_char",
    "c_bool",
    "c_void",
    "void"
]